Does not use eval for code evaluation for if/unless options
heartcombo/has_scope pull request #119
Opened 2020-09-21 16:55 UTC by dbalexandre

The scope where `eval()` is being used here is okay, but using it for code evaluation is tricky. The changes in this PR casts the string value to symbol and uses the `send()` method to determine if the scope should be applied or not.

2020-09-21 23:03 UTC, carlosantoniodasilva requested changes
Thanks @dbalexandre!

While I'm generally :+1: on stopping the usage of `eval` there, we might need a deprecation cycle instead of removing it directly, because the current `eval` implementation allows for custom code in the string there. (not just a method dispatch)

It looks like we don't have a test for this case, so I went ahead and pushed one: 4b8f5937a1916be2eceb2981f324ca465580d1ca. 

That test should fail on this branch with the removal of `eval`, with something like a `NoMethodError` or similar I think.

Would you like to implement a deprecation in there instead, for the time being? It might be a good timing, I'm hoping to release 0.8 at some point soon with some changes already in master + this PR: https://github.com/heartcombo/has_scope/pull/118.

2020-09-22 13:35 UTC, dbalexandre commented
@carlosantoniodasilva Thanks for the review. I'll implement the deprecation as you suggested 👍

2020-09-23 13:21 UTC, ggrocco approved these changes

2021-01-22 20:20 UTC, merged

2021-01-22 20:20 UTC, carlosantoniodasilva commented
Thanks @dbalexandre